--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgagent; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA pgagent;


ALTER SCHEMA pgagent OWNER TO postgres;

--
-- Name: SCHEMA pgagent; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA pgagent IS 'pgAgent system tables';


--
-- Name: test; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA test;


ALTER SCHEMA test OWNER TO postgres;

--
-- Name: pgagent; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgagent WITH SCHEMA pgagent;


--
-- Name: EXTENSION pgagent; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgagent IS 'A PostgreSQL job scheduler';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: empresas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empresas (
    id_empresa integer NOT NULL,
    nombre character varying NOT NULL,
    identificador_fiscal character varying NOT NULL,
    fecha_alta timestamp without time zone NOT NULL,
    usuario_alta integer NOT NULL,
    fecha_baja timestamp without time zone,
    usuario_baja timestamp without time zone
);


ALTER TABLE public.empresas OWNER TO postgres;

--
-- Name: empresas_id_empresa_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empresas ALTER COLUMN id_empresa ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empresas_id_empresa_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id_usuario integer NOT NULL,
    nombre character varying NOT NULL,
    email character varying NOT NULL,
    fecha_alta timestamp without time zone NOT NULL,
    usuario_alta integer NOT NULL,
    fecha_baja timestamp without time zone,
    usuario_baja integer,
    tipo_usuario character varying NOT NULL
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- Name: usuarios_empresas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios_empresas (
    id_usuario_empresa integer NOT NULL,
    id_usuario integer NOT NULL,
    id_empresa integer NOT NULL,
    fecha_alta character varying NOT NULL,
    usuario_alta integer NOT NULL,
    usuario_baja character varying,
    fecha_baja character varying
);


ALTER TABLE public.usuarios_empresas OWNER TO postgres;

--
-- Name: TABLE usuarios_empresas; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.usuarios_empresas IS 'Relacion empresa-usuario';


--
-- Name: usuarios_empresas_id_usuario_empresa_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios_empresas ALTER COLUMN id_usuario_empresa ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_empresas_id_usuario_empresa_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: control_esquemas; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.control_esquemas (
    id_empresa integer NOT NULL,
    nombre_esquema character varying(50) NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE test.control_esquemas OWNER TO postgres;

--
-- Name: empresas; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.empresas (
    id_empresa integer NOT NULL,
    id_fiscal character varying(20) NOT NULL,
    nombre character varying(100) NOT NULL,
    email_contacto character varying(100) NOT NULL,
    telefono_contacto character varying(20) NOT NULL,
    nombre_contacto character varying(100) NOT NULL,
    fecha_alta timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_modificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE test.empresas OWNER TO postgres;

--
-- Name: empresas_id_empresa_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

CREATE SEQUENCE test.empresas_id_empresa_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE test.empresas_id_empresa_seq OWNER TO postgres;

--
-- Name: empresas_id_empresa_seq; Type: SEQUENCE OWNED BY; Schema: test; Owner: postgres
--

ALTER SEQUENCE test.empresas_id_empresa_seq OWNED BY test.empresas.id_empresa;


--
-- Name: fichajes; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.fichajes (
    id_fichaje integer NOT NULL,
    id_usuario integer,
    id_empresa integer,
    fecha_entrada timestamp without time zone NOT NULL,
    fecha_salida timestamp without time zone,
    ubicacion character varying(100)
);


ALTER TABLE test.fichajes OWNER TO postgres;

--
-- Name: fichajes_id_fichaje_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

CREATE SEQUENCE test.fichajes_id_fichaje_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE test.fichajes_id_fichaje_seq OWNER TO postgres;

--
-- Name: fichajes_id_fichaje_seq; Type: SEQUENCE OWNED BY; Schema: test; Owner: postgres
--

ALTER SEQUENCE test.fichajes_id_fichaje_seq OWNED BY test.fichajes.id_fichaje;


--
-- Name: usuarios; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.usuarios (
    id_usuario integer NOT NULL,
    nombre character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    dni character varying(20) NOT NULL,
    fecha_alta timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_usuario_alta integer,
    fecha_modificacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_usuario_modificacion integer,
    fecha_baja timestamp without time zone,
    id_usuario_baja integer
);


ALTER TABLE test.usuarios OWNER TO postgres;

--
-- Name: usuarios_empresas; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.usuarios_empresas (
    id_usuario integer NOT NULL,
    id_empresa integer NOT NULL,
    rol character varying(50) NOT NULL,
    fecha_asignacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE test.usuarios_empresas OWNER TO postgres;

--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

CREATE SEQUENCE test.usuarios_id_usuario_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE test.usuarios_id_usuario_seq OWNER TO postgres;

--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE OWNED BY; Schema: test; Owner: postgres
--

ALTER SEQUENCE test.usuarios_id_usuario_seq OWNED BY test.usuarios.id_usuario;


--
-- Name: empresas id_empresa; Type: DEFAULT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.empresas ALTER COLUMN id_empresa SET DEFAULT nextval('test.empresas_id_empresa_seq'::regclass);


--
-- Name: fichajes id_fichaje; Type: DEFAULT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.fichajes ALTER COLUMN id_fichaje SET DEFAULT nextval('test.fichajes_id_fichaje_seq'::regclass);


--
-- Name: usuarios id_usuario; Type: DEFAULT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.usuarios ALTER COLUMN id_usuario SET DEFAULT nextval('test.usuarios_id_usuario_seq'::regclass);


--
-- Data for Name: pga_jobagent; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_jobagent (jagpid, jaglogintime, jagstation) FROM stdin;
9988	2024-12-22 12:53:11.424724+01	DESKTOP-OLGU325
\.


--
-- Data for Name: pga_jobclass; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_jobclass (jclid, jclname) FROM stdin;
\.


--
-- Data for Name: pga_job; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_job (jobid, jobjclid, jobname, jobdesc, jobhostagent, jobenabled, jobcreated, jobchanged, jobagentid, jobnextrun, joblastrun) FROM stdin;
\.


--
-- Data for Name: pga_schedule; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_schedule (jscid, jscjobid, jscname, jscdesc, jscenabled, jscstart, jscend, jscminutes, jschours, jscweekdays, jscmonthdays, jscmonths) FROM stdin;
\.


--
-- Data for Name: pga_exception; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_exception (jexid, jexscid, jexdate, jextime) FROM stdin;
\.


--
-- Data for Name: pga_joblog; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_joblog (jlgid, jlgjobid, jlgstatus, jlgstart, jlgduration) FROM stdin;
\.


--
-- Data for Name: pga_jobstep; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_jobstep (jstid, jstjobid, jstname, jstdesc, jstenabled, jstkind, jstcode, jstconnstr, jstdbname, jstonerror, jscnextrun) FROM stdin;
\.


--
-- Data for Name: pga_jobsteplog; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_jobsteplog (jslid, jsljlgid, jsljstid, jslstatus, jslresult, jslstart, jslduration, jsloutput) FROM stdin;
\.


--
-- Data for Name: empresas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.empresas (id_empresa, nombre, identificador_fiscal, fecha_alta, usuario_alta, fecha_baja, usuario_baja) FROM stdin;
1	root	1	2024-12-21 22:22:36.35176	1	\N	\N
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id_usuario, nombre, email, fecha_alta, usuario_alta, fecha_baja, usuario_baja, tipo_usuario) FROM stdin;
26	root	jesus_caba_mendez@hotmail.com	2024-12-24 18:25:14.323136	1	\N	\N	0
\.


--
-- Data for Name: usuarios_empresas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios_empresas (id_usuario_empresa, id_usuario, id_empresa, fecha_alta, usuario_alta, usuario_baja, fecha_baja) FROM stdin;
8	26	1	2024-12-24 18:25:33.968042+01	1	\N	\N
\.


--
-- Data for Name: control_esquemas; Type: TABLE DATA; Schema: test; Owner: postgres
--

COPY test.control_esquemas (id_empresa, nombre_esquema, fecha_creacion) FROM stdin;
\.


--
-- Data for Name: empresas; Type: TABLE DATA; Schema: test; Owner: postgres
--

COPY test.empresas (id_empresa, id_fiscal, nombre, email_contacto, telefono_contacto, nombre_contacto, fecha_alta, fecha_modificacion) FROM stdin;
\.


--
-- Data for Name: fichajes; Type: TABLE DATA; Schema: test; Owner: postgres
--

COPY test.fichajes (id_fichaje, id_usuario, id_empresa, fecha_entrada, fecha_salida, ubicacion) FROM stdin;
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: test; Owner: postgres
--

COPY test.usuarios (id_usuario, nombre, email, dni, fecha_alta, id_usuario_alta, fecha_modificacion, id_usuario_modificacion, fecha_baja, id_usuario_baja) FROM stdin;
1	administrador	admin@admin.com	123a	2024-12-15 18:07:22.445725	1	\N	\N	\N	\N
\.


--
-- Data for Name: usuarios_empresas; Type: TABLE DATA; Schema: test; Owner: postgres
--

COPY test.usuarios_empresas (id_usuario, id_empresa, rol, fecha_asignacion) FROM stdin;
\.


--
-- Name: empresas_id_empresa_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.empresas_id_empresa_seq', 1, true);


--
-- Name: usuarios_empresas_id_usuario_empresa_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_empresas_id_usuario_empresa_seq', 8, true);


--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_usuario_seq', 26, true);


--
-- Name: empresas_id_empresa_seq; Type: SEQUENCE SET; Schema: test; Owner: postgres
--

SELECT pg_catalog.setval('test.empresas_id_empresa_seq', 1, false);


--
-- Name: fichajes_id_fichaje_seq; Type: SEQUENCE SET; Schema: test; Owner: postgres
--

SELECT pg_catalog.setval('test.fichajes_id_fichaje_seq', 1, false);


--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE SET; Schema: test; Owner: postgres
--

SELECT pg_catalog.setval('test.usuarios_id_usuario_seq', 1, false);


--
-- Name: empresas empresas_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresas
    ADD CONSTRAINT empresas_pk PRIMARY KEY (id_empresa);


--
-- Name: empresas empresas_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresas
    ADD CONSTRAINT empresas_unique UNIQUE (identificador_fiscal);


--
-- Name: usuarios_empresas usuario_empresa_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_empresas
    ADD CONSTRAINT usuario_empresa_pk PRIMARY KEY (id_usuario_empresa);


--
-- Name: usuarios usuarios_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pk PRIMARY KEY (id_usuario);


--
-- Name: usuarios usuarios_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_unique UNIQUE (email);


--
-- Name: control_esquemas control_esquemas_nombre_esquema_key; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.control_esquemas
    ADD CONSTRAINT control_esquemas_nombre_esquema_key UNIQUE (nombre_esquema);


--
-- Name: control_esquemas control_esquemas_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.control_esquemas
    ADD CONSTRAINT control_esquemas_pkey PRIMARY KEY (id_empresa, nombre_esquema);


--
-- Name: empresas empresas_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.empresas
    ADD CONSTRAINT empresas_pkey PRIMARY KEY (id_empresa);


--
-- Name: fichajes fichajes_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.fichajes
    ADD CONSTRAINT fichajes_pkey PRIMARY KEY (id_fichaje);


--
-- Name: usuarios usuarios_dni_key; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.usuarios
    ADD CONSTRAINT usuarios_dni_key UNIQUE (dni);


--
-- Name: usuarios usuarios_email_key; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.usuarios
    ADD CONSTRAINT usuarios_email_key UNIQUE (email);


--
-- Name: usuarios_empresas usuarios_empresas_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.usuarios_empresas
    ADD CONSTRAINT usuarios_empresas_pkey PRIMARY KEY (id_usuario, id_empresa);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario);


--
-- Name: idx_control_esquemas_nombre_esquema; Type: INDEX; Schema: test; Owner: postgres
--

CREATE INDEX idx_control_esquemas_nombre_esquema ON test.control_esquemas USING btree (nombre_esquema);


--
-- Name: idx_dni; Type: INDEX; Schema: test; Owner: postgres
--

CREATE INDEX idx_dni ON test.usuarios USING btree (dni);


--
-- Name: idx_email; Type: INDEX; Schema: test; Owner: postgres
--

CREATE INDEX idx_email ON test.usuarios USING btree (email);


--
-- Name: idx_empresas_nombre; Type: INDEX; Schema: test; Owner: postgres
--

CREATE INDEX idx_empresas_nombre ON test.empresas USING btree (nombre);


--
-- Name: idx_fichajes_fecha_entrada; Type: INDEX; Schema: test; Owner: postgres
--

CREATE INDEX idx_fichajes_fecha_entrada ON test.fichajes USING btree (fecha_entrada);


--
-- Name: idx_fichajes_id_empresa; Type: INDEX; Schema: test; Owner: postgres
--

CREATE INDEX idx_fichajes_id_empresa ON test.fichajes USING btree (id_empresa);


--
-- Name: idx_fichajes_id_usuario; Type: INDEX; Schema: test; Owner: postgres
--

CREATE INDEX idx_fichajes_id_usuario ON test.fichajes USING btree (id_usuario);


--
-- Name: idx_usuarios_empresas_id_empresa; Type: INDEX; Schema: test; Owner: postgres
--

CREATE INDEX idx_usuarios_empresas_id_empresa ON test.usuarios_empresas USING btree (id_empresa);


--
-- Name: idx_usuarios_empresas_id_usuario; Type: INDEX; Schema: test; Owner: postgres
--

CREATE INDEX idx_usuarios_empresas_id_usuario ON test.usuarios_empresas USING btree (id_usuario);


--
-- Name: usuarios_empresas fk_id_empresa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_empresas
    ADD CONSTRAINT fk_id_empresa FOREIGN KEY (id_empresa) REFERENCES public.empresas(id_empresa);


--
-- Name: usuarios_empresas fk_id_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_empresas
    ADD CONSTRAINT fk_id_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);


--
-- Name: control_esquemas control_esquemas_id_empresa_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.control_esquemas
    ADD CONSTRAINT control_esquemas_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES test.empresas(id_empresa);


--
-- Name: fichajes fichajes_id_empresa_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.fichajes
    ADD CONSTRAINT fichajes_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES test.empresas(id_empresa);


--
-- Name: fichajes fichajes_id_usuario_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.fichajes
    ADD CONSTRAINT fichajes_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES test.usuarios(id_usuario);


--
-- Name: usuarios fk_usuario_alta; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.usuarios
    ADD CONSTRAINT fk_usuario_alta FOREIGN KEY (id_usuario_alta) REFERENCES test.usuarios(id_usuario);


--
-- Name: usuarios fk_usuario_baja; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.usuarios
    ADD CONSTRAINT fk_usuario_baja FOREIGN KEY (id_usuario_baja) REFERENCES test.usuarios(id_usuario);


--
-- Name: usuarios fk_usuario_modificacion; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.usuarios
    ADD CONSTRAINT fk_usuario_modificacion FOREIGN KEY (id_usuario_modificacion) REFERENCES test.usuarios(id_usuario);


--
-- Name: usuarios_empresas usuarios_empresas_id_empresa_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.usuarios_empresas
    ADD CONSTRAINT usuarios_empresas_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES test.empresas(id_empresa);


--
-- Name: usuarios_empresas usuarios_empresas_id_usuario_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.usuarios_empresas
    ADD CONSTRAINT usuarios_empresas_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES test.usuarios(id_usuario);


--
-- PostgreSQL database dump complete
--

