# Configuración global de Nginx

# Bloque de eventos
events {
    worker_connections 1024;  # Ajusta según sea necesario
}

# Configuración del servidor HTTP
http {
    # Configuración de logs (opcional)
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Otras configuraciones de http pueden ir aquí...

    # Bloque server
    server {
        listen 80;

        # Servir los archivos estáticos de React desde el contenedor de Nginx
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri /index.html;  # Permite navegación usando react-router
        }


        # Redirigir las solicitudes de la API a la aplicación Node.js
        location /api/ {
            proxy_pass http://localhost:5000;  # El contenedor backend Node.js
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
